pipeline {
	agent any
	stages {
		stage('build') {
		    steps{
		        sh 'echo "this is build stage"'
		    }
		}
		stage('test') {
		    steps{
		        sh 'echo "this is test stage"'
		    }
		}
		stage('deploy') {
		    steps{
		        sh 'echo "this is deploy stage"'
		    }
		}
	}
}
