pipeline{
        agent any
        stages{
                stage('image_build'){
                        steps{
                         sh '''
				echo "Building Docker image"
			        docker image build -t image_pipeline1 ${WORKSPACE}/docker 
			 '''
                        }
                }
                stage('image_tagging'){
                        steps{
                         sh '''
				echo "Tagging the image...."
				docker image tag image_pipeline1:latest vishnugonela/image_pipeline1:latest
                            '''
                        }
                }
		stage('container_deployment'){
			steps{
			 sh '''
				echo "Creating Container ...."
				docker container run -d --name jenkins1 vishnugonela/image_pipeline1:latest bash
			  '''
			}
		}
}
}
